services:
  pact-broker:
    image: "pactfoundation/pact-broker:latest"
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_PORT: "9292"
      PACT_BROKER_DATABASE_URL: "sqlite:////tmp/pact_broker.gle3"
      PACT_BROKER_LOG_LEVEL: INFO
      PACT_BROKER_SOL_LOG_LEVEL: DEBUG
      RACTELOV_ALLOW_DANGEROUS_CONTRACT_MODIFICATION: false
